// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nizamy-theme/DeepNavy.tsx": () => import("../components/mockups/nizamy-theme/DeepNavy.tsx"),
  "./components/mockups/nizamy-theme/RefinedBlue.tsx": () => import("../components/mockups/nizamy-theme/RefinedBlue.tsx"),
  "./components/mockups/nizamy-theme/WarmAiry.tsx": () => import("../components/mockups/nizamy-theme/WarmAiry.tsx")
};
